# Generated by Django 5.2.9 on 2025-12-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('course_outcomes', models.TextField()),
                ('num_classes', models.IntegerField()),
                ('class_duration', models.IntegerField()),
                ('class_size', models.IntegerField()),
                ('roadmap', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=200)),
                ('progress_percent', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherCourse',
        ),
    ]
